# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Métropolibre
tagline:          "la cité libre"
description:      "La cité libre de Métropolibre, jeu de rôle persistant en ligne mêlant exploration et politique au sein d'une cité-état tentaculaire."
url:              http://smwhr.github.io/metropolibre
baseurl:          /metropolibre

author:
  name:           'smwhr'
  url:            https://smwhr.net

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/smwhr/metropolibre
